[package]
name = "ndef-app"
version = "0.1.0"
authors = ["Conor Patrick <conor@solokeys.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.6"
heapless-bytes = "0.2.0"

apdu-dispatch = {path = "../apdu-dispatch"}
iso7816 = { path = "../iso7816" }
