[package]
name = "iso14443"
version = "0.0.1"
authors = ["Conor Patrick <conor@solokeys.com>"]
edition = "2018"

[dependencies]
delog = "0.1.0-alpha.3"
heapless = "0.5.6"
heapless-bytes = "0.1.1"
nb = "1"

apdu-dispatch = { path = "../apdu-dispatch" }
iso7816 = {path = "../iso7816"}
interchange = "0.1.0"

[features]
default = []

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []
